### ISSUE TITLE
Προβλημα με την εξοδο απο λογαριασμο.

### ISSUE THREAD

**Issue by ManosGEM** [gunet/openeclass#1]
Οταν κανεις  εισοδο με το account σου , αν κανεις αποσυνδεση-εξοδο απο το λογαριασμο σου και χωρις να κλεισεις τον browser πατησεις εισοδο ξανα (και ας εχεις κλεισει το tab και ανοιξεις νεο) , σε βαζει αυτοματα στο τελευταιο account απο το οποιο εκανες εξοδο. Ουσιαστικα αν δεν κλεισεις ολο τον browser δεν γινεται εξοδος απο το λογαριασμο σου. 
Το προβλημα το παρατηρησα στους εξης browsers : Internet Explorer , Google Chrome , Mozilla Firefox (win7 & ubuntu linux 14) .

απο αυτα που ξερω περι του θεματος , δεν γινεται σωστα το κλεισιμο του session.

**Comment by adia** [comment]
Επειδή δεν μπορέσαμε να αναπαραγάγουμε το πρόβλημα, μπορείτε να μας δώσετε κάποιες λεπτομέρειες ακόμα για τη συγκεκριμένη εγκατάσταση;
Καταρχάς, η σύνδεση χρήστη γίνεται με username/password από τη φόρμα σύνδεσης του eClass (και αν ναι, με username/password εσωτερικό της πλατφόρμας ή με LDAP ή άλλο τρόπο); Ή χρησιμοποιείται CAS ή Shibboleth;
Αν ισχύει το δεύτερο, τότε ισχύουν τα εξής: Στο CAS, θα πρέπει να ορίσετε το single-sign-out URL στις ρυθμίσεις του τρόπου πιστοποίησης - αλλιώς, ακόμα και όταν αποσυνδέεται κάποιος από το eClass, δεν αποσυνδέεται από το CAS provider, και έτσι πατώντας «Είσοδος» ο χρήστης ξαναπιστοποιείται και ξανασυνδέεται. Στο Shibboleth, δυστυχώς δεν υπάρχει από όσο ξέρουμε τρόπος να αποσυνδεθεί τελείως ο χρήστης, και έτσι ο μόνος τρόπος είναι να κλείσει το browser.
Αν μας δώσετε και τη διεύθυνση όπου τρέχει το eClass, θα μπορέσουμε να δούμε κι εμείς ποιοι τρόποι πιστοποίησης χρησιμοποιούνται.
Ευχαριστούμε!

**Comment by ManosGEM** [comment]
μπαινω στο eclass.teicrete.gr 
το θεμα το ειδα στη συνδεση με CAS.
το Shibboleth φανταζομαι ειναι αυτο που λεει με credentials, εκει πατησα εξοδος και οταν πατησα ξανα συνδεση με credentials δεν ειχε θεμα ειχε γινει εξοδος κανονικα..
μαλλον λοιπον παραμενει η πιστοποιηση απο το CAS provider. 
ευχαριστώ.

**Comment by adia** [comment]
Ευχαριστούμε για την ενημέρωση! Θα ειδοποιήσουμε τους διαχειριστές του eclass.teicrete.gr για να κάνουν τη σχετική ρύθμιση.
