### ISSUE TITLE
Δυνατότητα διαλειτουργικότητας openeclass με SEB Server / SafeExamBrowser

### ISSUE THREAD

**Issue by billtzim** [gunet/openeclass#107]
Καλησπέρα σας

θα ήθελα να προτείνω να διερευνήσετε την πιθανότητα συνεργασίας με τους δημιουργούς του SafeExamBrowser(SEB) και του SEB Server. Θα μπορούσε το openeclass να είναι ένα από τα υποστηριζόμενα LMS (είναι ήδη κάποια γνωστά όπως το Moodle, openedx κτλ) και υπάρξει ανάλογη δημιουργία module για την επικοινωνία με το SEB Server. Στην έκδοση του SEB Server 2.0 παρέχεται και η δυνατότητα proctoring, κάτι που σε συνεργασία με το openeclass LMS θα πρόσφερε προστιθέμενη αξία και στα δύο λογισμικά.

Παρακάτω μερικοί σύνδεσμοι σχετικά με το τα SEB και SEB Server για διευκόλυνσή σας.

1. [SafeExamBrowser](https://safeexambrowser.org/)
2. [SEB Server manual](https://seb-server.readthedocs.io/en/latest/index.html)
3. [SEB Server Github](https://github.com/SafeExamBrowser/seb-server)
4. [Moodle plugin](https://github.com/ethz-let/moodle-quizaccess_sebserver)

Ευχαριστώ πολύ
ΒΤ

**Comment by jexi** [comment]
Καλησπέρα.

Ευχαριστούμε για τις προτάσεις. Τα παραπάνω τα έχουμε σκεφτεί και εμείς. Πιστεύουμε ότι σε μελλοντική έκδοση της πλατφόρμας θα παρέχουμε υποστήριξη με SEB Server.

Φιλικά
