### ISSUE TITLE
Installed with errors on exercise module

### ISSUE THREAD

**Issue by yurtseverfazli** [gunet/openeclass#108]
It was installed it successfully? But produced the following error too.
In file G:\laragon\www\eclass\install\install_db.php on line 1227 : Unable to execute statement:"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''options' TEXT DEFAULT NULL, 'is_exam' INT DEFAULT 0 NULL) DEFAULT CHARACTER' at line 25", sqlstate:"1064", errornum:"42000", statement:"CREATE TABLE IF NOT EXISTS `exercise` ( `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `course_id` INT(11) NOT NULL, `title` VARCHAR(255) DEFAULT NULL, `description` TEXT, `type` TINYINT(4) UNSIGNED NOT NULL DEFAULT 1, `range` TINYINT UNSIGNED DEFAULT 0, `start_date` DATETIME DEFAULT NULL, `end_date` DATETIME DEFAULT NULL, `temp_save` TINYINT(1) NOT NULL DEFAULT 0, `time_constraint` INT(11) DEFAULT 0, `attempts_allowed` INT(11) DEFAULT 0, `random` SMALLINT(6) NOT NULL DEFAULT 0, `shuffle` SMALLINT(6) NOT NULL DEFAULT 0, `active` TINYINT(4) DEFAULT NULL, `public` TINYINT(4) NOT NULL DEFAULT 1, `results` TINYINT(1) NOT NULL DEFAULT 1, `score` TINYINT(1) NOT NULL DEFAULT 1, `assign_to_specific` TINYINT NOT NULL DEFAULT 0, `ip_lock` TEXT NULL DEFAULT NULL, `password_lock` VARCHAR(255) NULL DEFAULT NULL, `continue_time_limit` INT(11) NOT NULL DEFAULT 0, `calc_grade_method` TINYINT DEFAULT 1, `general_feedback` TEXT DEFAULT NULL, 'options' TEXT DEFAULT NULL, 'is_exam' INT DEFAULT 0 NULL) DEFAULT CHARACTER SET=utf8mb4 COLLATE utf8mb4_bin ENGINE=InnoDB", elapsed:1731409054.0008

Deprecated: Implicit conversion from float 1731453222.3 to int loses precision in G:\laragon\www\eclass\include\main_lib.php on line 2918
In file G:\laragon\www\eclass\install\install_db.php on line 2602 : Unable to execute statement:"Table 'eclass.exercise' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"CREATE INDEX `exer_index` ON exercise (course_id)", elapsed:1731409110.0009

As a result it works properly except the exercices module. How can I over come this? Or could you suggest a way to me to overcome the issue? It is the software I do need for my website. Thanks the creators.

**Comment by jexi** [comment]
Hi

Table `exercise` has not been created. The correct sql statement concerning table `exercise` is the following:

```
CREATE TABLE `exercise` (
  `id` int NOT NULL AUTO_INCREMENT,
  `course_id` int NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci,
  `type` tinyint unsigned NOT NULL DEFAULT '1',
  `range` tinyint DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `temp_save` tinyint(1) NOT NULL DEFAULT '0',
  `time_constraint` int DEFAULT '0',
  `attempts_allowed` int DEFAULT '0',
  `random` smallint NOT NULL DEFAULT '0',
  `shuffle` smallint NOT NULL DEFAULT '0',
  `active` tinyint DEFAULT NULL,
  `public` tinyint NOT NULL DEFAULT '1',
  `results` tinyint(1) NOT NULL DEFAULT '1',
  `score` tinyint(1) NOT NULL DEFAULT '1',
  `ip_lock` text CHARACTER SET ascii COLLATE ascii_bin,
  `password_lock` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `assign_to_specific` tinyint NOT NULL DEFAULT '0',
  `continue_time_limit` int NOT NULL DEFAULT '0',
  `calc_grade_method` tinyint DEFAULT '1',
  `general_feedback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci,
  `options` text COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `exer_index` (`course_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```
You can run the query either from mysql command line or from an administration mysql tool

The above error has been fixed in the forthcoming version 4.0.

Regards
