### ISSUE TITLE
Admin announcements missing class Indexer

### ISSUE THREAD

**Issue by Corfiot** [gunet/openeclass#22]
[Mon Feb 24 14:24:12.320411 2020] [:error] [pid 24003] [client 195.130.127.100:34946] PHP Fatal error:  Uncaught Error: Class 'Indexer' not found in /var/www/html/openeclass-3.7.6/modules/admin/adminannouncements.php:51\nStack trace:\n#0 {main}\n  thrown in /var/www/html/openeclass-3.7.6/modules/admin/adminannouncements.php on line 51, referer: https://v-class.avarts.ionio.gr/modules/admin/adminannouncements.php

Autoloader fail?

Patched with:
require_once 'modules/search/indexer.class.php';

**Comment by Corfiot** [comment]
Also Log class, patched with include/log.class.php

**Comment by jexi** [comment]
Fixed !
Thanks!
