### ISSUE TITLE
New user registration fails

### ISSUE THREAD

**Issue by Corfiot** [gunet/openeclass#23]
DB possibly does not support never expiring user accounts. This option is enabled in our system.
Patched with: ALTER TABLE `user` CHANGE `expires_at` `expires_at` DATETIME NULL;
(removed non-null requirement)

https://v-class.avarts.ionio.gr/modules/auth/newuser.php:

In file /var/www/html/openeclass-3.7.6/modules/auth/newuser.php on line 437 : Unable to execute statement:"Column 'expires_at' cannot be null", sqlstate:"1048", errornum:"23000", statement:"INSERT INTO user (surname, givenname, username, password, email, status, am, phone, registered_at, expires_at, lang, verified_mail, whitelist, description) VALUES (?, ?, ?, '<hash here>', ?, 5, ?, ?, FROM_UNIXTIME(1582548167), FROM_UNIXTIME(4171956167), ?, 0, '', '')", elapsed:1582548167.0015

In file /var/www/html/openeclass-3.7.6/include/lib/user.class.php on line 55 : Unable to execute statement:"Column 'user' cannot be null", sqlstate:"1048", errornum:"23000", statement:"INSERT INTO user_department (user, department) VALUES (?, ?)", elapsed:1582548167.0012

**Comment by jexi** [comment]
We can't reproduce the above error. What `user registration config options` are enabled? What exactly are the actions being made to trigger the error ?

BTW during user registration, always a value is assigned in `expires_at` field . The expiration of account (or not) is handled internally from the platform.

**Comment by Corfiot** [comment]
New user settings attached.
![Untitled](https://user-images.githubusercontent.com/1024087/75186462-98284e80-5750-11ea-9505-89493d451a97.png)

Reproduce:
1. Register as new student: provide external email (not LDAP registration)
2. Confirmation link sending page shows errors as reported above
3. Link does not work (because it was never written to the DB)

**Comment by Corfiot** [comment]
Note: link was sent via mail anyway, confusing users when it didn't work afterwards. A transaction could be useful here

**Comment by jexi** [comment]
The problem is that you have defined `duration account` = 999 (!). 
That is, it is converted internally in unix timestamp. 
But mysql statement 

> SELECT FROM_UNIXTIME(4172030038)

 returns 

> null

 (probably out of bounds!). So a mysql error is triggered.

Temporary solution: Remove 999 to something more logical :-)
A better solution will be soon commited.
Thanks!

**Comment by Corfiot** [comment]
You are right, I didn't notice the timestamp conversion. January 19, 2038 is the unix timestamp time limit. This is why it overflows.

The DB table column is DATETIME so why bother with the unix timestamp conversion? You could rework the query from DBHelper::timeAfter() -> DBHelper::timeAfter(get_config('account_duration')) to something like CURRENT_DATE() -> DATE_ADD(CURRENT_DATE(),INTERVAL get_config('account_duration') month)

If you don't trust the SQL server's date you could set the first date via date('Y-m-d') and change the query to something like SELECT DATE($x) AS a,DATE_ADD(DATE($x),INTERVAL 999 month)

I'd go for the second one to keep dates consistent through timezones, I think your date authority is the web server.

Are pull requests welcome?

**Comment by jexi** [comment]
The first solution doesn't work with Daylight Savings. (that is, are completely ignored). 

The second solution seems right but it requires some small changes in _DBHelper::timeAfter()_ . 
But we would prefer to not change something in core library without extensive testing :-)
