### ISSUE TITLE
Platform sends new user password in plaintext

### ISSUE THREAD

**Issue by Corfiot** [gunet/openeclass#24]
Registration confirmation request email sends username and password in plaintext to user during registration, when requesting activation via mail_verify.php link. This is obviously insecure and undesirable. This should at least be made configurable.

Changing this in the translation files is not possible. It's hardcoded.
Patched in:
modules/admin/newuseradmin.php <- removed password line from email body
NOT in modules/admin/multireguser.php <- seems like platform-set p/w, still insecure tho

Ο λογαριασμός σας στην πλατφόρμα AVARTS v-class

Τα προσωπικά στοιχεία του λογαριασμού σας είναι τα εξής:

    Όνομα χρήστη (username): <username here>
    Συνθηματικό (password): <plaintext password here>
    Διεύθυνση AVARTS v-class: https://....

**Comment by jexi** [comment]
It has been fixed in the forthcoming release 3.8.

**Comment by jexi** [comment]
closed

**Comment by jexi** [comment]
close
