### ISSUE TITLE
Error during upgrade

### ISSUE THREAD

**Issue by dyrer** [gunet/openeclass#28]
I have problem during upgrade from 3.4 to 3.7.6 with new table creation.

`eclass/upgrade/upgrade.php on line 3399 : Unable to execute statement:"Can't create table `eclass_edb`.`activity_content` (errno: 150 "Foreign key constraint is incorrectly formed")", sqlstate:"1005", errornum:"HY000", statement:"CREATE TABLE IF NOT EXISTS `activity_content` ( `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `course_id` INT(11) NOT NULL, `heading_id` INT(11) NOT NULL DEFAULT 0, `content` TEXT NOT NULL, FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE, FOREIGN KEY (heading_id) REFERENCES activity_heading(id) ON DELETE CASCADE, UNIQUE KEY `heading_course` (`course_id`,`heading_id`)) DEFAULT CHARACTER SET=utf8 ENGINE=InnoDB", elapsed:1584752226.0874`
and more tables for badges

I use mariadb 10.3 and also tested with mysql 5.6

**Comment by adia** [comment]
It's possible that the `course.id` field doesn't have the correct type, perhaps due to a bug in an old version of the platform. You could check the type to see if this is indeed the problem, and then  fix it. Then, you can set back the schema version and re-run the upgrade:

```SQL
SHOW CREATE TABLE course;
ALTER TABLE course MODIFY id INT(11) NOT NULL AUTO_INCREMENT;
UPDATE config SET value = '3.4' WHERE `key` = 'version';
```

**Comment by dyrer** [comment]
I dont have only one table with that problem 
do i have to to do one by one?
