### ISSUE TITLE
Blank screen on logout

### ISSUE THREAD

**Issue by NikosKeyz** [gunet/openeclass#3]
I get a blank screen on logout for every logged in account I have try.
![screenshot](https://cloud.githubusercontent.com/assets/9785225/13718758/b2d3184c-e7f5-11e5-9d52-973b051085dd.png)  
  
In error.log there is this

> [Sat Mar 12 01:58:56.692052 2016] [:error] [pid 10725] [client ::1:40121] PHP Fatal error:  Uncaught exception 'Exception' with message 'Hybridauth Library needs the CURL PHP extension.' in /var/www/html/openeclass/modules/auth/methods/hybridauth/Hybrid/Auth.php:127\nStack trace:\n#0 /var/www/html/openeclass/modules/auth/methods/hybridauth/Hybrid/Auth.php(55): Hybrid_Auth::initialize(Array)\n#1 /var/www/html/openeclass/index.php(106): Hybrid_Auth->__construct(Array)\n#2 {main}\n  thrown in /var/www/html/openeclass/modules/auth/methods/hybridauth/Hybrid/Auth.php on line 127, referer: http://localhost/openeclass/main/portfolio.php

**Comment by adia** [comment]
Hi Nikos! As the message says, you need to have the curl PHP extension installed in your web server. Apart from Hybridauth, there are other places Open eClass needs it, so it warns you during installation and upgrade if it's missing.

It's usually available as a package on Linux (e.g. php5-curl in Debian) or it might just be disabled so make sure it's installed and enabled. Feel free to contact us again if you need any help!

**Comment by NikosKeyz** [comment]
I have the php5-curl extention installed. 
Actually the problem came from "lamp-server^" package, which is available on *buntu repositories.
I think that you have to add a note on installation guide, warning users about this lamp installation method.
