### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by chrisagelou** [gunet/openeclass#30]
On a fresh installation of version 3.8 the following errors occur.  (table assignment can't be created)
Server info:
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.10
5.5.64-MariaDB

> In file /var/www/html/eclass-e-dimotiko-eu/install/install_db.php on line 975 : Unable to execute statement:"Invalid ON UPDATE clause for 'start_date_review' column", sqlstate:"1294", errornum:"HY000", statement:"CREATE TABLE IF NOT EXISTS `assignment` ( `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `course_id` INT(11) NOT NULL, `title` VARCHAR(200) NOT NULL DEFAULT '', `description` TEXT NOT NULL, `comments` TEXT NOT NULL, `submission_type` TINYINT NOT NULL DEFAULT '0', `deadline` DATETIME NULL DEFAULT NULL, `late_submission` TINYINT NOT NULL DEFAULT '0', `submission_date` DATETIME NOT NULL, `active` CHAR(1) NOT NULL DEFAULT '1', `secret_directory` VARCHAR(30) NOT NULL, `group_submissions` CHAR(1) DEFAULT '0' NOT NULL, `grading_type` TINYINT NOT NULL DEFAULT '0', `max_grade` FLOAT DEFAULT '10' NOT NULL, `grading_scale_id` INT(11) NOT NULL DEFAULT '0', `assign_to_specific` CHAR(1) DEFAULT '0' NOT NULL, `file_path` VARCHAR(200) DEFAULT '' NOT NULL, `file_name` VARCHAR(200) DEFAULT '' NOT NULL, `auto_judge` TINYINT(1) NOT NULL DEFAULT 0, `auto_judge_scenarios` TEXT, `lang` VARCHAR(10) NOT NULL DEFAULT '', `notification` TINYINT(4) DEFAULT 0, `ip_lock` TEXT, `password_lock` VARCHAR(255) NOT NULL DEFAULT '', `assignment_type` TINYINT NOT NULL DEFAULT '0', `lti_template` INT(11) DEFAULT NULL, `launchcontainer` TINYINT DEFAULT NULL, `tii_feedbackreleasedate` DATETIME NULL DEFAULT NULL, `tii_internetcheck` TINYINT NOT NULL DEFAULT '1', `tii_institutioncheck` TINYINT NOT NULL DEFAULT '1', `tii_journalcheck` TINYINT NOT NULL DEFAULT '1', `tii_report_gen_speed` TINYINT NOT NULL DEFAULT '0', `tii_s_view_reports` TINYINT NOT NULL DEFAULT '0', `tii_studentpapercheck` TINYINT NOT NULL DEFAULT '1', `tii_submit_papers_to` TINYINT NOT NULL DEFAULT '1', `tii_use_biblio_exclusion` TINYINT NOT NULL DEFAULT '0', `tii_use_quoted_exclusion` TINYINT NOT NULL DEFAULT '0', `tii_exclude_type` VARCHAR(20) NOT NULL DEFAULT 'none', `tii_exclude_value` INT(11) NOT NULL DEFAULT '0', `reviews_per_assignment` int(4) DEFAULT NULL, `start_date_review` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, `due_date_review` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP) DEFAULT CHARACTER SET=utf8 ENGINE=InnoDB", elapsed:1585855867.0006
> 
> In file /var/www/html/eclass-e-dimotiko-eu/install/install_db.php on line 1989 : Unable to execute statement:"Table 'dimotiko_eclass1.assignment' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"CREATE INDEX `assignment_index` ON assignment(course_id)", elapsed:1585855873.0004
> 
> In file /var/www/html/eclass-e-dimotiko-eu/install/install_db.php on line 2057 : Unable to execute statement:"Table 'dimotiko_eclass1.assignment' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"CREATE INDEX `deadline_dates` ON assignment (course_id, deadline)", elapsed:1585855875.0003
> 
> In file /var/www/html/eclass-e-dimotiko-eu/install/install_db.php on line 2112 : Unable to execute statement:"Table 'dimotiko_eclass1.assignment' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"CREATE INDEX `assignment_deadline` ON assignment (deadline)", elapsed:1585855876.0003

**Comment by jexi** [comment]
Use mysql version >= 5.6
