### ISSUE TITLE
Table Loginout Doesn't exist

### ISSUE THREAD

**Issue by tonyspanos** [gunet/openeclass#34]
Fresh install 3.8.1 , Ubuntu Server 20.04 LTS, Apache 2.4.41, MySQL 8.0.20, PHP 7.4.10

Constant error on top off the page

In file /var/www/html/blabla/include/main_lib.php on line 1004 : Unable to execute statement:"Table 'eclass.loginout' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"SELECT DATE_FORMAT(MAX(`when`), '%Y-%m-%d') AS last_login FROM loginout WHERE id_user = ? AND action = 'LOGIN'", elapsed:1590431995.0005

In file /var/www/html/blabla/main/portfolio.php on line 280 : Unable to execute statement:"Table 'eclass.loginout' doesn't exist", sqlstate:"1146", errornum:"42S02", statement:"SELECT * FROM loginout WHERE id_user = ? ORDER by idLog DESC LIMIT 1", elapsed:1590431995.0004

Please advise.

**Comment by adia** [comment]
Thanks for the report! Indeed, there was a syntax error in the loginout table definition. We have just released version 3.8.2 which fixes this, but if you want to avoid a reinstallation, you can run the following MySQL command:
```sql
CREATE TABLE `loginout` (
  `idLog` mediumint(9) unsigned NOT NULL AUTO_INCREMENT,
  `id_user` mediumint(9) unsigned NOT NULL DEFAULT 0,
  `ip` char(45) NOT NULL DEFAULT '0.0.0.0',
  `when` datetime NOT NULL,
  `action` enum('LOGIN','LOGOUT') NOT NULL DEFAULT 'LOGIN',
  PRIMARY KEY (`idLog`),
  KEY `i_loginout` (`id_user`),
  KEY `i_action` (`action`),
  KEY `id_user` (`id_user`),
  KEY `loginout_id` (`id_user`),
  KEY `loginout_ia` (`id_user`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
