### ISSUE TITLE
Hierarchy will not load properties, Can't edit or properly display in tree

### ISSUE THREAD

**Issue by dexter93** [gunet/openeclass#38]
It seems that hierarchy will not load any attributes. Default ones are shown, but can't be edited ( blank fields). Can't make new ones that respect their parents in the tree.

Using Apache, php 7.4.5, MariaDB 10.3.23 and the latest commit on master aafb424a9c401727b61e30a14a6fa1194f952183

` PHP Notice:  Trying to get property 'allow_user' of non-object in /var/www/eclass/modules/admin/hierarchy.php on line 316, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'visible' of non-object in /var/www/eclass/modules/admin/hierarchy.php on line 353, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'code' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 13, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'name' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 24, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'description' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 39, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'allow_course' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 61, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'allow_user' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 70, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'order_priority' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 79, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'lft' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 121, referer: http://127.0.0.1/modules/admin/hierarchy.php
 PHP Notice:  Trying to get property 'rgt' of non-object in /var/www/eclass/storage/views/9edd517d19f1b49900f4d90ca88972c17094099a.php on line 122, referer: http://127.0.0.1/modules/admin/hierarchy.php`

**Comment by jexi** [comment]
έχει διορθωθεί
