### ISSUE TITLE
When exporting the grades for a "Work", empty lines exist in the CSV

### ISSUE THREAD

**Issue by nplatis** [gunet/openeclass#42]
I graded one of the "Works" submitted by my students and then I exported the grades. The CSV file produced has empty lines between the lines of the entries.

Also some sorting (e.g. by surname) of the entries would be welcome.

E-Class 3.9.3

**Comment by jexi** [comment]
Η εξαγωγή βαθμών πλέον γίνεται σε αρχείο .xlsx
