### ISSUE TITLE
Prevent user select in exercises

### ISSUE THREAD

**Issue by sintoris** [gunet/openeclass#48]
Currently it is trivial for students to copy&paste a question in the exercises tool do a quick search in the web.

For programming questions, students can just run the provided code and choose the answer.

Implementing this should be trivial, with the CSS property [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select).

**Comment by jexi** [comment]
Έχει υλοποιηθεί (ως επιλογή) στην έκδοση 3.16

**Comment by jexi** [comment]
Έχει υλοποιηθεί (ως επιλογή) στην έκδοση 3.16
