### ISSUE TITLE
Αυτόματος κριτής - μόνιμο tooltip

### ISSUE THREAD

**Issue by sintoris** [gunet/openeclass#53]
Όπως φαίνεται στην εικόνα το tooltip "διαγραφή" δεν φεύγει και κρύβει τα σχετικά "Χ"

![image](https://user-images.githubusercontent.com/5039603/137166521-d4d4a82f-20bd-4ddf-ae18-fb300e83d592.png)

**Comment by jexi** [comment]
Έχει διορθωθεί
