### ISSUE TITLE
Missing CSRF Token at all form POST action in on Application

### ISSUE THREAD

**Issue by noobpk** [gunet/openeclass#54]
Hi
I found a CSRF vulnerability in your app a few months ago but still haven't received your confirmation on Huntr. Could you take a moment to confirm my report.?
Disclosure: https://huntr.dev/bounties/5d03e113-a60e-4190-b973-43c84412b02f/

Thanks ^^!!

**Comment by adia** [comment]
Sure! I just did - sorry for missing this step.
