### ISSUE TITLE
Table 'eclass.widget_widget_area' doesn't exist

### ISSUE THREAD

**Issue by katsos** [gunet/openeclass#6]
Καλησπέρα. 
Έχω εγκαταστήσει την έκδοση default από τον hg.gunet server σε δύο συστήματα και στα δύο έχω το πρόβλημα του τίτλου. Μπήκα με command line στην βάση μου και όντως ο πίνακας δεν υπάρχει.
To ένα σύστημα ήταν debian 8 και το άλλο linux mint 18.

**Comment by adia** [comment]
Συγνώμη για το πρόβλημα! Σε κάποιο merge εκ παραδρομής είχε διαγραφεί ο κώδικας που δημιουργεί τον πίνακα αυτό. Το διορθώσαμε στο commit 8ed8f50003078dc77db17ade7cf19960b892ef60. Δοκιμάστε μια νέα εγκατάσταση και θα πρέπει να είναι εντάξει.

Ευχαριστούμε για την αναφορά του προβλήματος!
