### ISSUE TITLE
nginx: 502 Bad Gateway

### ISSUE THREAD

**Issue by ziogaschr** [gunet/openeclass#8]
Καλημέρα σας,
έχω εγκαταστήσει την έκδοση 3.4.2 και σε διάφορες σελίδες (τυχαία) μου επιστρέφει `nginx: 502 Bad Gateway`. Τις περισσότερες φορές συμβαίνει κατά το login του χρήστη.

Έχω ακολουθήσει τις οδηγίες εγκαταστάσεις. Ωστόσο επειδή δεν μου επιτρέπεται να πειράξω το `nginx.conf` προσπάθησα να το κάνω με `.htaccess`.

Αν εξαιρέσουμε το 502 όλα παίζουν σωστά και μπορώ να περιηγηθώ σε όλες τις σελίδες.
Στα logs του server δεν μπόρεσα να εντοπίσω κάποιο πρόβλημα.

Ευχαριστώ

**Comment by adia** [comment]
Καλησπέρα!

Καταρχάς, να επισημάνουμε ότι, από όσο γνωρίζουμε, ο nginx δεν υποστηρίζει .htaccess, οπότε αν χρειάζεται κάποια ρύθμιση θα πρέπει να γίνει αλλιώς.

Το πρόβλημα δεν το έχουμε συναντήσει, όμως πιθανόν να οφείλεται σε κάποια αστάθεια της σύνδεσης του nginx με το php-fpm - αυτό χρησιμοποιείτε για υποστήριξη PHP, σωστά;

Δείτε μήπως κάποιο σχετικό σφάλμα εμφανίζεται στο log του php-fpm και όχι σε αυτό του nginx.

Κάποιες συζητήσεις που βρήκαμε προτείνουν να γυρίσετε τη σύνδεση από unix domain socket σε TCP.  Επίσης και στην παρακάτω συζήτηση αναφέρονται κάποιες αλλαγές στις ρυθμίσεις που πιθανόν να βοηθήσουν:

http://stackoverflow.com/questions/10003978/php-fpm-and-nginx-502-bad-gateway

**Comment by ziogaschr** [comment]
Αυτό που έκανα είναι να προσπαθήσω να βάλω τον κανόνα για 404 στο .htaccess που υπάρχει στην [ενότητα 1.1.2](http://docs.openeclass.org/el:install_doc).

Ναι php-fpm χρησιμοποιούμε.

> Δείτε μήπως κάποιο σχετικό σφάλμα εμφανίζεται στο log του php-fpm και όχι σε αυτό του nginx

Κοίταξα όλα τα logs και αυτά τις php.

Θα δοκιμάσω να γυρίσω σε TCP.

Ευχαριστώ πολύ

**Comment by adia** [comment]
Κλείνουμε την αναφορά καθώς δεν είχαμε κάτι νεώτερο. Αν παρατηρήσετε ξανά το πρόβλημα, παρακαλούμε ενημερώστε μας. Ευχαριστούμε!
