### ISSUE TITLE
Δεν στέλνονται ενημερώσεις μέσω email στους φοιτητές για σχόλια στις εργασίες

### ISSUE THREAD

**Issue by nplatis** [gunet/openeclass#81]
Σε εργασία που έχω δημιουργήσει, προσπαθώ να στείλω σχόλια στους φοιτητές.

Σενάριο 1: 
Για μία υποβολή εργασίας, πατάω το μολυβάκι («Διόρθωση») και βλέπω τη σελίδα της συγκεκριμένης υποβολής. Προσθέτω κάποια σχόλια ή/και βαθμό ή/και αρχείο με σχόλια. Το checkbox «Ενημέρωση μέσω ηλεκτρονικού ταχυδρομείου» είναι ενεργοποιημένο. Πατάω «Καταχώριση αλλαγών». 
Ο φοιτητής δεν λαμβάνει ποτέ κανένα email με τα σχόλια ή τον βαθμό μου.

Σενάριο 2:
Στη σελίδα με όλες τις υποβολές της εργασίας (με το checkbox «Ειδοποίηση χρηστών μέσω ηλεκτρονικού ταχυδρομείου» ενεργοποιημένο), πατάω «Καταχώριση αλλαγών». Οι φοιτητές που έχουν βαθμό (είτε γιατί τον καταχώρισα στη σελίδα αυτή είτε γιατί τον είχα καταχωρίσει στη σελίδα της δικής τους υποβολής, όπως στο Σενάριο 1), λαμβάνουν email το οποίο αναφέρει μόνο τον βαθμό τους, ενώ το πεδίο «Σχόλια» υπάρχει στο email αλλά είναι κενό, ενώ δεν υπάρχει αναφορά στο αν υπάρχει αρχείο με σχόλια.

Προφανώς, το αναμενόμενο είναι οι φοιτητές να λαμβάνουν ένα πλήρες email με σχόλια, αρχείο σχολίων (συνημμένο, ή έστω ως σύνδεσμο) και βαθμό, κάθε φορά που γίνονται αλλαγές (εφόσον το σχετικό checkbox είναι ενεργοποιημένο).

Τα παραπάνω αφορούν στην εγκατάσταση του eclass στο Πανεπιστήμιο Πελοποννήσου (έκδοση 3.13.2) αλλά φαίνεται να είναι γενικότερο θέμα. Δεν υπάρχει τεχνικό ζήτημα με την αποστολή email στους φοιτητές από το eclass καθώς αυτοί λαμβάνουν email από τη σελίδα υποβολής της εργασίας (Σενάριο 2), καθώς και ανακοινώσεις κ.λπ.

**Comment by jexi** [comment]
έχει διορθωθεί στην έκδοση 3.15
